# Generated by Django 5.0.6 on 2024-07-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='calories',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='burger',
            name='material',
            field=models.CharField(default='Not specified', max_length=500),
        ),
        migrations.AddField(
            model_name='pizza',
            name='calories',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='material',
            field=models.CharField(default='Not specified', max_length=500),
        ),
    ]
