# Generated by Django 5.0.6 on 2024-07-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_burger_calories_burger_material_pizza_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Momos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=4)),
                ('material', models.CharField(default='Not specified', max_length=500)),
                ('calories', models.CharField(blank=True, max_length=50, null=True)),
                ('mimg', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=4)),
                ('material', models.CharField(default='Not specified', max_length=500)),
                ('calories', models.CharField(blank=True, max_length=50, null=True)),
                ('simg', models.URLField()),
            ],
        ),
    ]
