# Generated by Django 5.0.6 on 2024-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_momos_sandwich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momos',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
