# Generated by Django 5.0.6 on 2024-07-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_momos_pricel_alter_burger_pricel_alter_burger_pricem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momos',
            name='priceL',
        ),
    ]
